### ISSUE TITLE
Eyo! Your key pressed event runs too many times!

### ISSUE THREAD

**Issue by Rikthepixel** [CodingWithMenno/ByteCat#1]
![afbeelding](https://user-images.githubusercontent.com/63408969/162592585-becd82b8-1d1c-44b5-b3d5-fae25c0e9631.png)

**Comment by M-e-n-n-o** [comment]
Hey, in the KeyPressedEvent there is a "isRepeat()" method you can call to see if the event is a repeated event. This should solve your issue :)
